### ISSUE TITLE
Abstract the fetch mockery code

### ISSUE THREAD

**Issue by emirotin** [resin-io-modules/resin-request#85]
Maybe we could just expose a method that says `installMocks` that would return a properly configured `fetchMock` instance as well as setup all the expected things.

Or just abstract the setup code to a single submodule and expose a method `setFetch`.

See this thread: https://github.com/resin-io-modules/resin-pine/pull/25

**Comment by emirotin** [comment]
Hey @pimterry after thinking more about it I think we may have a problem.
That wasn't the case with mocking the global `fetch` but now as we have to plug it into the request module this won't work for the sub-dependencies.
Imagine this graph:
```
A -> B -> resin-request (1)
 \-> C -> resin-request (2)
```
npm _may_ not lift both instances of `resin-request`, especially if incompatible versions are requested.
Now if the tests in A try to setup the mock for resin-request it will only work for the module in `A/node_modules/resin-request`. Thus mocking the endpoints used by `C` may not happen.

DI is one of the obvious solutions to the problem but I don't like the idea of changing the code because of the tests requirements.

Am I missing something?

**Comment by pimterry** [comment]
@emirotin Yep, that's a problem - there's nothing we can do to guarantee we get a single resin-request instance: http://justjs.com/posts/singletons-in-node-js-modules-cannot-be-trusted-or-why-you-can-t-just-do-var-foo-require-baz-init. Generally, the recommended way to deal with this is dependency injection (as that article mentions, this is what express etc do).

I'm fine with DI. I wouldn't think of it in terms of changing for the tests; it's simply a change that allows the downstream consumer (be that tests, or a real downstream module) to decide and configure the resin-request you use. That's useful even without this: it means the downstream module is responsible for the resin-request setup, and responsible for deciding which version to use (so it also becomes the one single place we normally have to change to upgrade resin-request everywhere).

It becomes essential anyway for some kinds of options actually already. If you want to turn on `debug` for all resin requests at the moment, you can't, because each module manages its own. And in fact this has just shown me a potential bug: all the modules already building their own resin-request's (e.g. [resin-pine](https://github.com/resin-io-modules/resin-pine/blob/master/lib/pine.coffee#L41)) take and set up only with `dataDirectory`. They don't take or use `isBrowser`, which means they have `stream()` defined when used in the browser (where it'll try to require `rindle`, and crash). 

DI's a good thing regardless of testing, and would also make all this testing logic simpler as a bonus. I'm getting more and more convinced that we should just do it.

**Comment by emirotin** [comment]
>  And in fact this has just shown me a potential bug: all the modules already building their own resin-request's (e.g. resin-pine) take and set up only with dataDirectory. They don't take or use isBrowser, which means they have stream() defined when used in the browser

Wait, don't they pass the entire options object down the stream?

In general if you think the DI should be used OK let's switch to it.
My biggest concern is that with the _push_ model we split the knowledge. Right now every module defines and manages its dependencies, just by CommonJS+npm design.
With DI the consumer is now responsible for knowing which deps should be injected where. And the SDK for instance will have to be very careful with the order of instantiating all the deps.
With singleton instances we will also have troubles with circular deps.

If you know the answers to the abovementioned concerns (some elegant DI container to use instead of orchestrating the things ourselves) let's try. I'm willing to finalize the SDK thing as soon as possible, but obviously reliable tests are the must.

Just for reference I have already implemented a kind of DI in the SDK PR, with circular deps issue being solved by deferred evaluation. But it was easier as all the dependencies are local to the SDK project.

**Comment by emirotin** [comment]
> Wait, don't they pass the entire options object down the stream?

ADD: if they don't they should start doing regardless

**Comment by pimterry** [comment]
> In general if you think the DI should be used OK let's switch to it.

I can get all the PRs updated to inject resin-request without much trouble at all. Are there any other dependencies that it's really important to have consistent between every module? Resin-token maybe? That would let us drop the dataDirectory argument totally for these sdk modules.

> With DI the consumer is now responsible for knowing which deps should be injected where. And the SDK for instance will have to be very careful with the order of instantiating all the deps.

I think this isn't too bad: every module's factory declares its runtime dependencies, so it's pretty explicit, within the module itself, and you just have to find an order that fulfills what every constructor is says it wants. As long as we don't go crazy that should be fairly easy I think.

> Circular dependencies

This bit is potentially painful. What circular dependencies do we have?

> If you know the answers to the abovementioned concerns (some elegant DI container to use instead of orchestrating the things ourselves) let's try.

I think we can keep this fairly simple, and we shouldn't need a fancy container framework. If we do, we've probably gone wrong. I'd like to just inject the one or two modules that we need to be consistent and shared between instances to start with. It doesn't need to be every single module right now or anything like that, and we can incrementally expand this later only when we need to.

> > Wait, don't they pass the entire options object down the stream?

> ADD: if they don't they should start doing regardless

I'm not sure that's true: modules could use the same option name differently, and providing a bunch of unrelated options to every module seems weird. Doesn't matter though, since this isn't a problem with DI (these options all get set once at the top level, not passed around).

**Comment by emirotin** [comment]
> Are there any other dependencies that it's really important to have consistent between every module? Resin-token maybe?

This is the only module that deals with storage. So indeed if it's injected preconfigured with the dataDIrectory all other modules can forget about this option wich is good.

I don't think there's another module like that. Here's the updated dependency diagram: https://resin-sdk-modules-kpjhjrzoxv.now.sh/. I may have missed something, but I believe it's accurate.

> What circular dependencies do we have?

Actually, I don't think we do now. It's the case with the SDK modules that I have solved and that made me cautious about using the DI.

> I'd like to just inject the one or two modules that we need to be consistent and shared between instances to start with.

Cool, let's try with the request and token modules and see how it goes. Refer to the same scheme above about the order of changes and the modules that need to be checked.

The change will result in new major versions. Please also check for reasonable dependencies updates, and write the most recent versions here [https://github.com/resin-io/resin-sdk/issues/221#issuecomment-252509879] after publishing.

> I'm not sure that's true: modules could use the same option name differently, and providing a bunch of unrelated options to every module seems weird.

Well, not blindly of course. But things like `debug` may need to be carefully sent down the stream.

**Comment by emirotin** [comment]
Closed by https://github.com/resin-io-modules/resin-request/pull/89
