### ISSUE TITLE
Default to native `fetch` when available?

### ISSUE THREAD

**Issue by emirotin** [resin-io-modules/resin-request#86]
The ponyfill module always returns the version based on XHR [https://github.com/qubyte/fetch-ponyfill/issues/21] which IMO can be less performant. Though we know that Edge 14 has some issues with its fetch implementation [https://github.com/qubyte/fetch-ponyfill/issues/9#issuecomment-253911888]

So should we default to the global fetch or not?
Doing so would also simplify the mocking a lot, right? We could just set the mocked fetch as global and voila.

@pimterry discuss :)

**Comment by pimterry** [comment]
> Doing so would also simplify the mocking a lot, right?

With the current approach, definitely.

If we move to DI (as in #85) then not much, it'd just be changing a single `request.setFetch(fetchMock)` into `globals.fetch = fetchMock`. Has the upside that you automatically every other instance of fetch used anywhere, but that's not necessarily always what you want. Less control, but maybe more helpful magic mocking in places. I'm on the fence on whether it's a good thing in that case.

> The ponyfill module always returns the version based on XHR which IMO can be less performant

Can it? I can't find any numbers one way or the other. I'd imagine XHR is pretty quick tbh, since it's been being heavily used and well optimized for quite some time, and under the hood it's making all the same requests (afaik?). I've done some research, but I can't seem to find any concrete analysis on downsides of the polyfilling this in the browser, rather than using the native implementation.

> So should we default to the global fetch or not?

I don't think it has any runtime benefits, it might have some testing benefits. We should decide on the DI stuff first, since I think that decides this for us. If we don't DI then we should definitely do this, if we do DI then we might want to do this but it's not very important.

**Comment by emirotin** [comment]
> and under the hood it's making all the same requests (afaik?).

I don't know the deep details, but at least to the Dev Tools they look different.
I assume the native implementation can be faster because of the specific optimization browser vendors can implement in C++ vs the userland wrapper on top of XHR that can be slower just because of several layer of JS functions.

> We should decide on the DI stuff first

Yes sure, let's continue in #85
