### ISSUE TITLE
Refused to set unsafe header "accept-encoding"

### ISSUE THREAD

**Issue by emirotin** [resin-io-modules/resin-request#91]
Reported here https://github.com/resin-io/resin-sdk/issues/257

@craig-mulligan what env does it happen in? Chrome? Node? Something else?

**Comment by craig-mulligan** [comment]
It's in chrome/safari, but I don't see the error in firefox though.

Everything works as expected just wondering why it's raising it.

Do you not see it in your tests?

**Comment by pimterry** [comment]
We do see it in our tests, annoyingly - see the linked issue above. It's just that we don't get errors in PhantomJS, because it's a little lax about such things.

My previous repro was running `./node_modules/.bin/karma start --no-single-run` from inside `resin-sdk` and then opening [localhost:9876/debug.html](http://localhost:9876/debug.html) in Chrome, which should start the tests and then throw this up at least once a second or so. All still passes, but you're right, it's messy and we should definitely fix it before 6.0.0 comes out of beta.

**Comment by emirotin** [comment]
Oh, didn't notice that issue before.
Well, we can try dropping this header and seeing if it still works.
It was required with `request` before

**Comment by emirotin** [comment]
I think it's fixed now @pimterry?

**Comment by pimterry** [comment]
Yep, missed linking this somehow. This was fixed by https://github.com/resin-io-modules/resin-request/pull/93.
